### ISSUE TITLE
Problem with calculation of the percentage

### ISSUE THREAD

**Issue by Sleis** [elementbound/scrumshowdown#3]
### Issue type

* [x] bug report

#### The problem
Using with 9 people the percentage of the votes are calculated in a way that the sum of the percentages is 99% instead of 100%.

#### Proposed solution
Easiest way is using an if statement to change the 99% to 100%, but
counting with less rounding can be a better solution.

#### Notes
For example.
We are 9. The rate of the votes is 3/6. In that case the percentages of the votes are the following: 33% and 66%. And of course these two numbers' sum is 99% and not 100%.

**Comment by elementbound** [comment]
Thanks for the ticket, @Sleis! The issue is fixed, and should be online in v1.14.2! 🙂
