### ISSUE TITLE
T-shirt size estimation method support

### ISSUE THREAD

**Issue by zoltan-pal** [elementbound/scrumshowdown#69]
### Issue type

* [ ] bug report
* [x] feature request

### Feature request

Please add support for t-shirt size estimation method

#### The problem

The tool supports estimations using the modified Fibonacci sequence only.

#### Proposed solution

Adding t-shirt sizing method would add some more flexibility to the tool.
Perhaps a new option selector could be added for the estimation methods, and the current dropdown menu would be populated based on the selected method.

**Comment by elementbound** [comment]
Good idea! I'll add a quick solution soon-ish and create some issues for a better integrated version.
